# Generated by Django 3.1.5 on 2021-07-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='_edits',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
